### ISSUE TITLE
I have a question about unsupported CPUs😀

### ISSUE THREAD

**Issue by ghost** [MTK-bypass/bypass_utility#110]
I am currently using two unsupported devices.
The final goal is to (bootloaderunlock)🙂

Model number mt8365v/mt8168
I have not been able to dump or unlock these two types of BROM.
It did not work with existing tools or payloads.😢
Is there a possibility that these two types of CPUs will be supported in the future?

I'm just an ordinary person with no skills or knowledge.
I can't do anything.
I hope mt8365v is supported🥲

**Comment by NasiGorengBurung** [comment]
You can find more payload from MTKclient, in mtkclient, you would find in payload folder
