### ISSUE TITLE
Stuck at "Waiting for bootrom" stage - Redmi Note 5

### ISSUE THREAD

**Issue by sirakai-pc** [MTK-bypass/bypass_utility#15]
Hello. I installed everything as instructions but it seems that the python scripts can't find my COM port. I also tried passing it as an argument:
`python  .\main.py -s COM4`
And it gives me this error:
`RuntimeError: Unexpected output, expected 0xfd got 0x4`
I also tried to check the code by myself but I sincerely don't understand how I should fix this.
I also tried to pass a non-existent COM port and it gives me another kind of error:
`serial.serialutil.SerialException: could not open port 'COM5': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)`

**Comment by sirakai-pc** [comment]
I downloaded the last version of the bypass scripts.. Now the error seems a permission one:
```
    raise SerialException("GetOverlappedResult failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: GetOverlappedResult failed (PermissionError(13, 'Access is denied.', None, 5))
```

**Comment by chaosmaster** [comment]
Are you sure your device is in BROM-mode?

**Comment by vungocmobile** [comment]
Redmi Note 5 is Qualcomm
