### ISSUE TITLE
Is it possible to flash the smartphone, even if the bootloader is locked?

### ISSUE THREAD

**Issue by Durelam** [MTK-bypass/bypass_utility#16]

**Comment by chaosmaster** [comment]
We're not using the bootloader for flashing, so yes!

**Comment by google-mirror** [comment]
> We're not using the bootloader for flashing, so yes!

Can we just unlock the bootloader?

**Comment by chaosmaster** [comment]
That would really depend on the device and how unlocking is implemented.
If it's just a simple flag on one of the partitions, then that is possible.
If it requires a signed unlock-token not so much.
