### ISSUE TITLE
it doesnt work on my redmi note 8 pro global

### ISSUE THREAD

**Issue by aria-7553** [MTK-bypass/bypass_utility#18]
basically a repost from the xda thread:

it's just stuck on waiting for device, i've tried everything like cmd in admin, restarting, all the debug parameters, even class filters. i dont see mtk6785t but 6785 is there so i think that shouldnt be an issue? idk but any help would be great, i have the payloads in the payloads/ folder and the default_config.json5 file in the dir with main.py in it

i'm running it on a pc w ryzen 5 3600 so that could be why? i've checked the code it seems to just not find the serial port. if i should try on an intel cpu, how would i use it with a mac? because i dont have any other pcs. maybe through vm but i doubt that'd work.

**Comment by chaosmaster** [comment]
Please don't crosspost, let's keep it on XDA, since this isn't an issue with the utility.
