### ISSUE TITLE
Protection Disabled but still getting STATUS_SEC_AUTH_FILE_NEEDED

### ISSUE THREAD

**Issue by Wh1terat** [MTK-bypass/bypass_utility#41]
<img width="859" alt="Screenshot 2021-06-28 at 01 06 37" src="https://user-images.githubusercontent.com/1288525/123563574-72301580-d7ad-11eb-932a-9d6ef3a987bf.png">

MT8167S variant, mt8167 payload seemingly works but SP Tool still reporting STATUS_SEC_AUTH_FILE_NEEDED on readback.

Any thoughts?

[bootrom_8167.bin.zip](https://github.com/MTK-bypass/bypass_utility/files/6722501/bootrom_8167.bin.zip)

**Comment by chaosmaster** [comment]
Was the device rebooted in between?
What DA are you using?
Please run the bypass a second time, providing the initially detected port via the `--serial_port` option and post the results.

**Comment by Wh1terat** [comment]
Device wasn't rebooted - but it didn't stay sat in brom, went back to fastboot before I could run it a second time.

**Comment by Wh1terat** [comment]
Also the -t dump doesn't seem to work, incomplete file of varying sizes - but always <2kb.

**Comment by chaosmaster** [comment]
Sounds like there may be an issue with the USB connection.
Maybe try different cables, ports, PC.

**Comment by Wh1terat** [comment]
I suspect you're right re PC.
(Was running under virtual environment).

Need to dig the brick laptop out of the garage to try.

Will mark as closed. Thanks.
