### ISSUE TITLE
Can possible daa & sla bypass/development payload for new mtk dimensity chips ?

### ISSUE THREAD

**Issue by Rony-21** [MTK-bypass/bypass_utility#43]
Like thats new mtk chips

Dimesity 700
Dimesity 800U
Dimesity 1000
Dimesity 1200

Becasue some paid tools added bypass funtion for dimesity chips

Please check developers and add new dimesity chips payload

**Comment by KondratokGK** [comment]
+1 MT6853

**Comment by sieger707** [comment]
MT6833 Dimensity 700  also included ? I dont see payload for that . Does that mean generic one will work ?
