### ISSUE TITLE
camellian redmi note  5g stuck reading emmc

### ISSUE THREAD

**Issue by koyuyesil** [MTK-bypass/bypass_utility#47]
![READ](https://user-images.githubusercontent.com/730999/129739200-38b63e97-70b3-4d55-b8a7-61534bf401da.PNG)
stopping reads after 14 mb reading

**Comment by chaosmaster** [comment]
That's not an issue with the bypass utility.
Please try different USB cables, ports or different PC.

**Comment by koyuyesil** [comment]
> That's not an issue with the bypass utility.
> Please try different USB cables, ports or different PC.

yes i checked problem %99 DA file
