### ISSUE TITLE
Getting S_DL_GET_DRAM_SETTING_FAIL from SPFT after using bypass_utility

### ISSUE THREAD

**Issue by Tooniis** [MTK-bypass/bypass_utility#57]
I'm getting `S_DL_GET_DRAM_SETTING_FAIL` after 11 seconds from starting a readback. I've set SPFT to UART connection on port /dev/ttyACM0 with baud rate 115200.

**Comment by chaosmaster** [comment]
Make sure to use the correct preloader and scatter-file for your device.
As this issue is unrelated to the bypass, I am closing it.

**Comment by Tooniis** [comment]
> Make sure to use the correct preloader

I think I'm missing a step here. So I was trying to readback while the device was in BROM after disabling DAA with bypass_utility. Do I need to load/boot/flash a preloader or something before using SPFT?
